[package]
name = "tagger-server"
description = "Image tagging webapp backend"
version = "0.1.0"
authors = ["Joel Dice <joel.dice@gmail.com>"]
edition = "2018"

[dependencies]
sqlx = { version = "0.5", features = [ "runtime-tokio-native-tls", "sqlite" ] }
anyhow = "1"
serde_json = "1"
warp = "0.3"
pretty_env_logger = "0.4"
log = "0.4"
mime = "0.3"
chrono = "0.4"
rexiv2 = "0.9"
regex = "1"
sha2 = "0.9"
futures = "0.3"
structopt = "0.3"
unicase = "2.6"
image = "0.23"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
