[package]
name = "render"
version = "0.1.0"
authors = ["Joel Dice <joel.dice@gmail.com>"]

[dependencies]
maplit = "*"
stdweb = { version = "*", optional = true }
im = { git = "https://github.com/bodil/im-rs", optional = true }
