[package]
name = "tagger-shared"
description = "Image tagging webapp shared code"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = "1"
serde_derive = "1"
lalrpop-util = "0.19"
chrono = { version = "0.4", features = [ "serde" ] }

[dev-dependencies]
maplit = "1"
anyhow = "1"

[build-dependencies]
lalrpop = "0.19"
